### ISSUE TITLE
Arduino : Defines serial ports

### ISSUE THREAD

**Issue by thactronika** [ActronikaSAS/libsmp#20]
The arduino-core introduces defines ("HAVE_HWSERIALx") for its AVR architectures but not its ARM one.
The problem is that these defines are used in libsmp to map the path to the port (i.e. "serial0" to Serial).
So when we try to compile for the ARM architectures, the library cannot be initialized, as those path are not recognized.

This problem has been seen for Arduino DUE and Teensy.

Moreover, Serial is not defined in HardwareSerial, so for this one, it is not recognized and so do not compile.
For the Arduino DUE it is defined in "variants/arduino_due_x/variant.h".
For Teensy, Serial is defined in "usb_serial.h"

**Comment by azanelli-actronika** [comment]
The associated commit should fix the issue, could you confirm for both platform ?
