### ISSUE TITLE
Exporting library for Arduino IDE

### ISSUE THREAD

**Issue by thactronika** [ActronikaSAS/libsmp#21]
When exporting the library for the Arduino IDE and using it to compile for Arduino DUE, we had a problem concerning the files included.

Indeed, this script exports what is needed for AVR, in particularly libsmp-private-avr.h that describe errors codes.
This file is included in libsmp-private if __AVR is defined, or for this architecture, but in our case this is not defined, which is still logic, but this way it is looking for libsmp-private-posix.h, that is not exported.

**Comment by azanelli-actronika** [comment]
Not relevent since 0.5.90 as libsmp-private-avr.h doesn't exist anymore.
